
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
  loki:
    image: grafana/loki:3.2.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
      - ./var/loki:/var/loki
    command: -config.file=/mnt/config/loki-config.yml
    networks:
      - my-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/mnt/config/promtail-config.yml
      - ./var/loki:/var/loki
    command: -config.file=/mnt/config/promtail-config.yml
    depends_on:
      - loki
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - my-network

volumes:
  grafana-storage: {}
  loki-data: {}

networks:
  my-network:
    driver: bridge