server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push #or 192.168.x.x

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - 192.168.56.1
        labels:
          job: varlogs
          __path__: /var/loki/chunks/*
